package com.werkpilot.audit.domain;

public enum AuditEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    USER_CREATED,
    USER_ROLE_CHANGED,
    USER_STATUS_CHANGED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    CSV_IMPORT_STARTED,
    CSV_IMPORT_FAILED,
    CSV_IMPORT_COMMITTED,
    CSV_IMPORT_CORRECTED,
    CSV_IMPORT_ROLLED_BACK,
    ANOMALY_STATUS_CHANGED,
    TICKET_STATUS_CHANGED,
    REPORT_GENERATED,
    THRESHOLD_DELEGATION_CHANGED,
    THRESHOLD_CHANGED,
    RETENTION_PURGE_EXECUTED
}
