package com.werkpilot.shared.error;

public enum ErrorCode {
    AUTH_INVALID_CREDENTIALS,
    AUTH_TOKEN_EXPIRED,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    VALIDATION_FAILED,
    CSV_MISSING_COLUMN,
    CSV_UNKNOWN_COLUMN,
    CSV_VALIDATION_FAILED,
    IMPORT_DUPLICATE_FILE,
    BUSINESS_RULE_VIOLATION,
    INTERNAL_ERROR
}
